#!/usr/bin/env python3
"""build_explainer_data.py — refresh the data snapshots the architecture explainer reads.

docs/explainer/ is a static site (GitHub Pages, no build step), so its charts read small JS
snapshots of the model's data files instead of the files themselves. Re-run this after any of
the source files below is rebuilt, then publish with scripts/publish-explainer.ps1.

  docs/explainer/assets/climate_zones.js      ← data/climate/tmy3_zones.json, zip_to_zone.json
  docs/explainer/assets/pvwatts.js            ← data/solar/pvwatts_zip.json (zone stations)
  docs/explainer/assets/nrel_profiles.js      ← data/loads/end_use_profiles.json (Jan + Jul rows)
                                                + data/rates/device_load_shapes.json (old shapes)
  docs/explainer/assets/projection_curves.js  ← data/rates/projection/whywatt_rate_projection.json
  docs/explainer/assets/tariff.js             ← data/rates/urdb_tou.json (PG&E default TOU plan)
                                                + data/rates/nbt_export_acc.json (2026, Jan + Jul)

Prose numbers written into pages by hand (not regenerated — review them when a source changes):
  pipelines/urdb.html (E-TOU-C table, fixed charge), appliances/battery.html (grid-charging table),
  pipelines/projection.html (decomposition bars), and the defaults quoted on appliance pages.

NOTHING here is imported by src/.

USAGE (from project root):
    .venv/Scripts/python.exe scripts/build_explainer_data.py
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).parent.parent
DATA = ROOT / "data"
OUT = ROOT / "docs" / "explainer" / "assets"

PGE_EIAID = "14328"
EXPORT_YEAR = "2026"          # first year of a run starting now; the hourly simulator's tariff year
SIM_MONTHS = (0, 6)           # January, July — the months the explainer's hourly views show


def _load(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def _r(a, nd=4):
    return [round(float(x), nd) for x in a]


def _js(obj) -> str:
    return json.dumps(obj, separators=(",", ":"), ensure_ascii=False)


def _write(name: str, header: str, body: str) -> None:
    path = OUT / name
    path.write_text(f"/* {header}\n   Generated by scripts/build_explainer_data.py — do not edit by hand. */\n{body}",
                    encoding="utf-8")
    print(f"  wrote {path.relative_to(ROOT)}  ({path.stat().st_size:,} bytes)")


def climate() -> None:
    z = _load(DATA / "climate" / "tmy3_zones.json")
    zips = _load(DATA / "climate" / "zip_to_zone.json")
    zones = [{
        "id": v["zone_id"], "city": v["reference_city"], "station": v["tmy3_station"],
        "hdd": v["monthly_hdd_65f"], "cdd": v["monthly_cdd_65f"],
        "inlet": v["monthly_inlet_water_f"], "temp": v["monthly_avg_temp_f"],
        "trend": {s: [v["hdd_cagr_by_scenario"][s], v["cdd_cagr_by_scenario"][s]] for s in ("rcp45", "rcp85")},
    } for k, v in z.items() if k != "_meta"]
    n_zip = len([k for k in zips if not k.startswith("_")])
    _write("climate_zones.js",
           f"Snapshot of data/climate/tmy3_zones.json ({z['_meta']['series']}, built {z['_meta']['built']}).",
           f"window.ZONES = {_js(zones)};\nwindow.ZIP_COUNT = {n_zip};\n")


def pvwatts() -> None:
    p = _load(DATA / "solar" / "pvwatts_zip.json")
    pv = {}
    for zone, ref in p["zones"].items():
        s = p["sites"][ref["site"]]
        sh = s["intraday_shape"]
        pv[zone] = {"ac": _r(s["ac_monthly"], 1), "jan": _r(sh[0]), "jun": _r(sh[5]), "jul": _r(sh[6]),
                    "dec": _r(sh[11]), "label": s["label"]}
    _write("pvwatts.js",
           f"Snapshot of data/solar/pvwatts_zip.json (NREL PVWatts v8, per 1 kW DC; built {p['_meta']['built']}).\n"
           "   Zone reference stations; Jan/Jun/Jul/Dec hourly shapes in local standard time.",
           f"window.PV = {_js(pv)};\nwindow.PV_ZIPS = {len(p['zips'])};\n")


def nrel() -> None:
    e = _load(DATA / "loads" / "end_use_profiles.json")
    old = _load(DATA / "rates" / "device_load_shapes.json")["profiles"]
    prof = {z: {u: {"jan": _r(v[0]), "jul": _r(v[6])} for u, v in eu.items()} for z, eu in e["profiles"].items()}
    n = {z: {u: note["buildings"] for u, note in eu.items()} for z, eu in e["_meta"]["notes"].items()}
    _write("nrel_profiles.js",
           f"Snapshot of data/loads/end_use_profiles.json (NREL ResStock 2025 R1, AMY2018; built {e['_meta']['built']}).\n"
           "   January and July rows, local standard time; plus the old data/rates/device_load_shapes.json.",
           f"window.NREL = {_js(prof)};\nwindow.NREL_N = {_js(n)};\n"
           f"window.OLD_SHAPES = {_js({k: _r(v) for k, v in old.items()})};\n")


def projection() -> None:
    b = _load(DATA / "rates" / "projection" / "whywatt_rate_projection.json")
    mk = b["markets"][b["default_market"]]
    years = [str(y) for y in range(b["horizon"][0], b["horizon"][1] + 1)]
    curves = {s: {f: [round(v["retail"][f][y], 4) for y in years] for f in ("elec", "gas")}
              for s, v in mk["scenarios"].items()}
    pac = mk["benchmarks"]["eia_pacific"]
    curves["eia_pacific"] = {f: [round(pac[f][y], 4) for y in years] for f in ("elec", "gas")}
    _write("projection_curves.js",
           f"Snapshot of data/rates/projection/whywatt_rate_projection.json ({b['default_market']} market, "
           f"nominal $; generated {b['generated_utc']}).",
           f"window.PROJ = {{years:[{','.join(years)}], base:{_js(mk['base_retail'])}, curves:{_js(curves)}}};\n")


def tariff() -> None:
    u = _load(DATA / "rates" / "urdb_tou.json")["utilities"][PGE_EIAID]
    t = u["tariffs"][u["default_label"]]
    months = [{"pk": [tier["rate"] for tier in m["peak"]],
               "op": [tier["rate"] for tier in m["offpeak"]],
               "base": m["peak"][0]["max_kwh_day"]} for m in t["by_month"]]
    fixed = t["fixed_charge"]
    assert fixed["unit"] == "$/day", fixed
    x = _load(DATA / "rates" / "nbt_export_acc.json")["by_year"][EXPORT_YEAR]
    plan = {"utility": u["utility"], "name": t["family"], "startdate": t["startdate"],
            "baseline_region": t["baseline_region"], "peak_hours": t["peak_hours"],
            "fixed_per_day": fixed["value"], "months": months}
    _write("tariff.js",
           f"Snapshot of data/rates/urdb_tou.json ({u['utility']} default plan {t['family']}, "
           f"region {t['baseline_region']}, effective {t['startdate']})\n"
           f"   and data/rates/nbt_export_acc.json (NEM 3.0 export $/kWh, {EXPORT_YEAR}, clock time).",
           f"window.TARIFF = {_js(plan)};\n"
           f"window.EXPORT = {_js({m: _r(x[m]) for m in SIM_MONTHS})};\n")


if __name__ == "__main__":
    print("Building explainer data snapshots…")
    climate(); pvwatts(); nrel(); projection(); tariff()
    print("Done. Publish with: powershell -ExecutionPolicy Bypass -File scripts\\publish-explainer.ps1")
